### ISSUE TITLE
Support for nicolaslopezj/roles 2.0

### ISSUE THREAD

**Issue by ashishapy** [nicolaslopezj/orion-users-with-roles-attribute#1]
Hi
I am getting error while updating nicolaslopezj/roles to version 2.0.1.

"=> Errors while adding packages:             

While selecting package versions:
error: Conflict: Constraint nicolaslopezj:roles@1.3.1 is not satisfied by
nicolaslopezj:roles 2.0.1.
Constraints on package "nicolaslopezj:roles":
- nicolaslopezj:roles@2.0.1 <- top level
- nicolaslopezj:roles@1.5.3 || 2.0.0 <- orionjs:base 1.6.0 <-
  nicolaslopezj:orion-users-with-roles-attribute 1.0.1
- nicolaslopezj:roles@1.3.1 <- nicolaslopezj:orion-users-with-roles-attribute
  1.0.1"

It seems orion-users-with-roles-attribute doesn't support roles 2.0 or further.

**Comment by nicolaslopezj** [comment]
With roles 2.0 there is no need for this package.
Just add the role as the filter, like this:

``` js
userId: orion.attribute('user', {
    label: 'User'
  }, {
    publicationName: 'anyUniqueStringHere',
    additionalFields: ['roles'],
    filter: function() {
      return { roles: 'admin' }; // or { roles: { $in: ['admin', 'editor'] } }
    }
  })
```
